### ISSUE TITLE
Rename plant subcommand to something more clear

### ISSUE THREAD

**Issue by narendasan** [arbor-dev/seedling#3]
It might make sense to rename ```plant``` to something more clear. Open to opinions.
IMO usage like ```seedling [name of project]``` is more straight forward with some sort of CLI form to fill out populating the project

**Comment by therishidesai** [comment]
Just doing `seedling [name of project]` is a little confusing. I initially used plant because it kinda goes with the theme. We could also do `seedling create [name of project]`. Another potential is just have the cli tool be called arbor.

**Comment by narendasan** [comment]
not sure why we need a sub command to do the main thing this application is supposed to do. We could maybe call the app ```plant``` or ```plant-seedling``` or something

**Comment by therishidesai** [comment]
I was thinking seedling/whatever we call it could have more future commands, like creating new services. Plant as a name may make more sense.

**Comment by narendasan** [comment]
Can you rename the repo and the executable? Alias what you have for the plant sub command to the root function (plant [name of api gateway application]) and then work on adding a sub command plant [service] to create a service.

**Comment by therishidesai** [comment]
Don't have permissions to change the name.
